config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :discussions
  resources :users
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :searches do
    member do
      post :do_searh
    end
  end

  # Defines the root path route ("/")
  root "movies#index"
end

app/views/layouts/_bottom_navbar.html.erb
<nav class="navbar fixed-bottom navbar-light d-lg-none " style="background: lightgrey">

  <div class="row container-fluid w-100 text-center m-1 p-0" >
    <div class="col p-1">
      <%= link_to root_path, class: "p-3 nav-icon" do %>
        <span class="material-icons">home</span>
      <% end %>
    </div>
    <div class="col p-1">
      <%= link_to searches_path, class:"p-3 nav-icon" do %>
        <span class="material-icons">search</span>
      <% end %>
    </div>
    <div class="col p-1">
      <%= link_to users_path, class:"p-3 nav-icon" do %>
        <span class="material-icons">person</span>
      <% end %>
    </div>
  </div>

</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path do %>
    <%= image_tag("logo.png", width: "200") %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="margin-left: 20px">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          Home <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to searches_path, class: "nav-link" do %>
          Result <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class: "nav-link" do %>
          User <span class="sr-only">(current)</span>
        <% end %>
      </li>
    </ul>
  </div>

  <div>
    <%= render 'searches/form' %>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalkAboutTheMovies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Google material icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>

    <%= render "layouts/navbar" %>
    <%= render "layouts/bottom_navbar" %>

    <div id="main-container" class="container mb-5 mb-lg-0" >
      <div id="main-row" class="row">
        <div id="left-col" class="col-0 col-md-2 p-0 m-0">
        </div>
        <div id="center-col" class="col">
          <div id="yield-container" class="container">
            <%= yield %>
          </div>
        </div>
        <div id="right-col" class="col-0 col-md-2 p-0 m-0">
        </div>
      </div>
    </div>

  </body>

</html>